import 'package:flutter/material.dart';

class AppColors{
  static final List<Color> backgroundColors = [
    Color(0xFFd1cdba),
    Color(0xFFDA976C),
    Color(0xFF473531),
    Color(0xFF3D372C),
    Color(0xFF646564),
    Color(0xFF58534C),
    Color(0xFF574949),
    Color(0xFFd1cdba),
    Color(0xFF5B4947),
    Color(0xFF6E4642),
    Color(0xFF4B3432),
    Color(0xFF322C24),
    Color(0xFF4D4633),
    Color(0xFFa39283),
    Color(0xFF7A655C),
  ];
  static final List<Color> borderColors = [
    Color(0xFFb5af95),
    Color(0xFFB35A2F),
    Color(0xFF2C1F1B),
    Color(0xFF1F1C14),
    Color(0xFF3C3D3C),
    Color(0xFF3A342E),
    Color(0xFF3A2B2B),
    Color(0xFFb5af95),
    Color(0xFF3E2F2D),
    Color(0xFF3C2825),
    Color(0xFF241A19),
    Color(0xFF181612),
    Color(0xFF383326),
    Color(0xFF726457),
    Color(0xFF5A4741),
  ];

  static final List<Color> textColors = [
    Colors.black,
    Colors.black,
    Colors.white,
    Colors.white,
    Colors.white,
    Colors.white,
    Colors.white,
    Colors.black,
    Colors.white,
    Colors.white,
    Colors.white,
    Colors.white,
    Colors.white,
    Colors.white,
    Colors.white,
  ];
  static final List<Color> cardColors = [
    Colors.white,
    Colors.white,
    Colors.black54,
    Colors.black54,
    Colors.black54,
    Colors.black54,
    Colors.black54,
    Colors.white,
    Colors.white,
    Colors.black54,
    Colors.black54,
    Colors.black54,
    Colors.black54,
    Colors.black54,
    Colors.black54,
  ];
  static final List<Color> iconColors = [
    Colors.black,
    Colors.black,
    Colors.white,
    Colors.white,
    Colors.white,
    Colors.white,
    Colors.white,
    Colors.black,
    Colors.black,
    Colors.white,
    Colors.white,
    Colors.white,
    Colors.white,
    Colors.white,
    Colors.white,
  ];

}