name: dia_dos_namorados
description: "Projeto para o dia dos namorados"
version: 1.0.1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  audioplayers: ^5.2.1
  device_preview: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  flutter_gen_runner:

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/musics/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
      - family: Roboto
        fonts:
          - asset: assets/fonts/Roboto-Bold.ttf
            weight: 700
          - asset: assets/fonts/Roboto-Medium.ttf
            weight: 500
          - asset: assets/fonts/Roboto-Regular.ttf.otf
            weight: 400
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
