name: dia_dos_namorados
description: "Projeto para o dia dos namorados"
version: 1.0.1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  audioplayers: ^5.2.1
  device_preview: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  flutter_gen_runner:

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/musics/
  fonts:
      - family: Roboto
        fonts:
          - asset: assets/fonts/Roboto-Bold.ttf
            weight: 700
          - asset: assets/fonts/Roboto-Medium.ttf
            weight: 500
          - asset: assets/fonts/Roboto-Regular.ttf
            weight: 400
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
